#
# This system-level configuration file is responsible for providing Boggart with
# its default set of supported languages and mutation operators. Please do not
# modify it! To add support for new languages and mutation operators to your
# local installation, you should provide a user-level configuration file.
#
# By default, Boggart looks for user-level configuration files at the path given
# by the environmental variable `BOGGART_USER_CONFIG_PATH`. If
# `BOGGART_USER_CONFIG_PATH` is undefined, `${HOME}/.boggart.yml` will be used
# instead.
#
version: '1.0'

languages:
  - name: C++
    file-endings:
      - .cpp
      - .cxx
      - .cc
  - name: C
    file-endings:
      - .c
  - name: Java
    file-endings:
      - .java
  - name: Python
    file-endings:
      - .py

operators:
  - name: NEGATE_IF_CONDITION_CSTYLE
    languages:
      - C
      - C++
      - Java
    transformations:
      - match: "if (:[1])"
        rewrite: "if (!(:[1]))"

  - name: delete-void-function-call
    languages:
      - C
      - C++
      - Java
    transformations:
      - match: ":[1]();"
        rewrite: ""
        constraints:
          - type: is-single-term
            hole: "1"
          - type: preceded-by
            any-of: [";", "{", "}"]

  - name: flip-arithmetic-operator
    languages:
      - C
      - C++
      - Java
    transformations:
      - match: "+"
        rewrite: "-"
      - match: "-"
        rewrite: "+"
      - match: "*"
        rewrite: "/"
      - match: "/"
        rewrite: "*"

  - name: flip-boolean-operator
    languages:
      - C
      - C++
      - Java
    transformations:
      - match: "&&"
        rewrite: "||"
      - match: "||"
        rewrite: "&&"

  - name: flip-relational-operator
    languages:
      - C
      - C++
      - Java
    transformations:
      - match: "<"
        rewrite: ">="
      - match: ">="
        rewrite: "<"
      - match: ">"
        rewrite: "<="
      - match: "<="
        rewrite: ">"
      - match: "=="
        rewrite: "!="
      - match: "!="
        rewrite: "=="

  - name: undo-transformation
    languages:
      - C
      - C++
      - Java
    transformations:
      - match: ":[1] = :[2](:[3]);"
        rewrite: ":[1] = :[3];"
        constraints:
          - type: is-single-term
            hole: "1"
          - type: is-single-term
            hole: "2"
          - type: is-single-term
            hole: "3"

  - name: delete-conditional-control-flow
    languages:
      - C
      - C++
      - Java
    transformations:
      - match: "if (:[1]) { return; }"
        rewrite: ""
      - match: "if (:[1]) return;"
        rewrite: ""
      - match: "if (:[1]) { break; }"
        rewrite: ""
      - match: "if (:[1]) break;"
        rewrite: ""

  - name: flip-signedness
    languages:
      - C
      - C++
    transformations:
      - match: "unsigned int :[1] ="
        rewrite: "int :[1] ="
